# Ryu SDN Example Guest -- for the FlowRider2020 example
# 

FROM ubuntu:19.10
RUN apt-get update
RUN apt-get install -qy --no-install-recommends dnsutils
RUN apt-get install -qy iputils-ping net-tools

